---
format:
  html:
    respect-user-color-scheme: true
    theme:
        light: ["style/flatly_customizations.scss", "style/style-light-color-customizations.scss", "style/style-customizations.scss"]
        dark: ["style/darkly_customizations.scss", "style/style-dark-color-customizations.scss", "style/style-customizations.scss"]
---

# Elementwise Operations with `.map()` {#sec-series-elementwise-operations-map}

```{python}
import pandas as pd
```


## Mapping Elements with a Function

Often, we will want to apply a function to each individual value in a series. As an example, let's take another look at the `durations_series` variable.

```{python}
durations_series = pd.Series(
    [60, 210, 120, 45],
    name="Duration in Minutes"
)
durations_series
```

We might want to display these activity durations in `h:mm` format instead of minutes. Let's write a function which takes a number of minutes and returns a string with the corresponding hours and minutes separated by a colon.

```{python}
#| lst-label: lst-series-define-function-for-mapping
#| lst-cap: Defining the function for formatting a duration nicely.
def minutes_to_hours_and_minutes(minutes):
    hours = minutes // 60
    minutes -= hours * 60

    return f"{hours}:{minutes:02}"

# trying out our function
minutes_to_hours_and_minutes(90)
```

In @lst-series-define-function-for-mapping, Python's `//` operator performs division, but gives the result without any decimal places. In the functions return statement, `:02` ensures that minutes are always displayed with two digits. If `minutes` is less than 10, then a leading zero will be shown. To apply the function we defined to each element in a series, we pass it to the series' `.map()` method.

```{python}
durations_series.map(minutes_to_hours_and_minutes)
```

<!-- ```{python}
[minutes_to_hours_and_minutes(minutes) for minutes in durations_series]
``` -->

::: {#exr-map-user-ids-to-names}

Can you apply a function to each of the elements of the following series?

```{python}
user_series = pd.Series(
    [42, 22, 1, 42],
    name="User ID"
)
```

The function should replace the user IDs 1, 22, and 42 with "Carl", "Barbara", and "Aleks", respectively.

```{python}
#| eval: false
user_series  # TODO
```

You can compare your solution to @sol-map-user-ids-to-names.
:::

## Mapping Elements with a Lambda Function

Instead of passing a function defined with `def` to `.map()`, we can also pass a lambda function. Let's see this in action using the time format example again.

```{python}
durations_series.map(lambda minutes:
    f"{minutes // 60}:{minutes - 60 * minutes // 60:02}"
)
```

It works and the code is more concise now 😊

<!-- ```{python}
[f"{minutes // 60}:{minutes - 60 * minutes // 60:02}" for minutes in durations_series]
``` -->

::: {#exr-map-user-ids-to-names-with-lambda}

Can you map user IDs to names as in @sec-exercise-map-user-ids-to-names, but this time using a lambda function?

```{python}
#| eval: false
user_series  # TODO
```

You can compare your solution to @sol-map-user-ids-to-names-with-lambda.
:::

## Mapping Elements with a Dictionary or Series

Changing the time formats above involved a calculation on each value in the `durations_series` variable. However, mapping user IDs to names does not really involve calculations; it's just a lookup operation. In such cases, we do not need to pass a function to the `.map()` method. A simple data structure such as a dictionary is enough.

```{python}
user_id_to_name_dict = {42: "Aleks", 22: "Barbara", 1: "Carl"}
user_series.map(user_id_to_name_dict)
```

::: {#exr-map-user-ids-to-names-with-series}

What if we had a series instead of a dictionary above with the series index and series elements corresponding to the dictionary keys and values, respectively? We can use it in place of the dictionary! Construct such a series and try it out 😉

```{python}
#| eval: false
user_id_to_names_series =  # TODO
user_series.map(user_id_to_names_series)
```

You can compare your solution to @sol-map-user-ids-to-names-with-series.
:::

<!-- TODO? Maybe in a future version also discuss `.replace()` considering [this](https://stackoverflow.com/a/62947436) nice answer on stackoverflow -->
