---
format:
  html:
    respect-user-color-scheme: true
    theme:
        light: ["style/flatly_customizations.scss", "style/style-light-color-customizations.scss", "style/style-customizations.scss"]
        dark: ["style/darkly_customizations.scss", "style/style-dark-color-customizations.scss", "style/style-customizations.scss"]
---

<!-- TODO: split this long chapter into two (1. getting elements by label and 2. by position) -->

# Getting Elements of a Series by Index Label {#sec-series-get-elements-loc-labels}

```{python}
import pandas as pd
```

## Getting a Single Element of a Series Using `.loc`

To obtain a specific element of a series, we can use the element's index label and pass it to the series' `.loc` property using square brackets (`[]`). We will see this in action using the `durations_series` once again.

```{python}
durations_series = pd.Series(
    [60, 210, 120, 45],
    name="Duration in Minutes"
)
durations_series
```

As we can see, the first element in `durations_series` has the index label `0`. Let's use this index to access the element!

```{python}
#| lst-label: lst-series-loc-single-label
#| lst-cap: Accessing a single value in a series.
durations_series.loc[0]
```

In @sec-series-non-numeric-index, we discussed that index labels are not necessarily numeric.

```{python}
row_series = pd.Series(
    [1, 42, "run", 60],
    index=["Activity ID", "User ID", "Activity Type", "Duration in Minutes"]
)
```

The `row_series` variable has strings as index labels, but this does not change how we access an element of the series – we simply use the index label. Let's access the duration stored in `row_series`.

```{python}
row_series.loc["Duration in Minutes"]
```

## Getting Multiple Elements of a Series Using `.loc`

### Using a List

We can also access multiple elements at once using `.loc[]`. To indicate that we want multiple elements of a series, we can use a list instead of a single index label. Let's have a look at the first two values stored in `durations_series`.

```{python}
durations_series.loc[[0, 1]]
```

Note that we now get a series as a result as opposed to @lst-series-loc-single-label where the result was just a single value. Let's try accessing multiple elements once more – this time with string indices.

```{python}
row_series.loc[
    ["Activity Type", "Duration in Minutes"]
]
```

### Using a Slice

Alternatively, we could use a slice to obtain multiple elements of a series.

```{python}
durations_series.loc[0:1]
```

::: callout-warning
Note that slicing using `.loc[start:end]` will always result in all elements from `start` to `end`, including *both* ends of the range. This is in sharp contrast to Python's standard behavior, which does not include the index indicating the interval's upper bound.
:::

While including the upper bound of the slice may feel unpythonic at first, it starts to make more sense, once we consider an index consisting of strings. If we want all columns ranging from `"User ID"` to `"Duration in Minutes"`, we probably want to have the latter included in the result.

```{python}
row_series.loc[
    "User ID":"Duration in Minutes"
]
```

To keep the behavior between integer and string indices consistent, indexing using `.loc` includes the upper bound of the slice irrespective of the index labels' data type.

Now, we have learned how to access elements using `.loc` and index labels 🎉️ Let's check out an alternative way to access series elements.

::: {#exr-series-loc-filter-with-list}

Use indexing with labels to get a series containing only those elements of `row_series` whose index label starts with the word *Activity*. A list of all index labels fulfilling the condition is already defined in the following code cell. All that is left to do, is to filter `row_series` using these labels.

```{python}
#| eval: false
labels = [
    label for label in row_series.index
    if label.startswith("Activity")
]
row_series  # TODO
```

<!-- TODO: make sure to mention that the index property can be simply accessed as done in the code cell above (using `series_variable.index`) -->

You can compare your solution to @sol-series-loc-filter-with-list.
:::
