---
format:
  html:
    respect-user-color-scheme: true
    theme:
        light: ["style/flatly_customizations.scss", "style/style-light-color-customizations.scss", "style/style-customizations.scss"]
        dark: ["style/darkly_customizations.scss", "style/style-dark-color-customizations.scss", "style/style-customizations.scss"]
---

# Changing a Plot's Layout {#sec-visualization-layout}

```{python}
import plotly.express as px
iris_df = px.data.iris()
```

## Title

The plots that Plotly produces look pretty good by default.

::: light-content
```{python}
#| echo: false
import plotly.io as pio
pio.templates.default = "plotly"
```
```{python}
fig = px.scatter(
    iris_df,
    x="petal_width",
    y="petal_length",
    color="species",
    opacity=0.5
)
fig
```
:::
::: dark-content
```{python}
#| echo: false
import plotly.io as pio
pio.templates.default = "plotly_dark"
```
```{python}
fig = px.scatter(
    iris_df,
    x="petal_width",
    y="petal_length",
    color="species",
    opacity=0.5
)
fig
```
:::

However, sometimes we might want to adjust the layout a bit. For instance, a good rule of thumb is to add a title to a plot. This helps the reader understand the depicted information more easily. For any layout-related changes, we use a figure's `update_layout` method.

```{python}
fig.update_layout(
  title_text="Comparison of petals of different Iris species"
)
```

## Axes Names

A second recommendation is to always choose descriptive names for the plot's axes. In our example, they are already easy to understand, however, the underscores in *petal_width* and *petal_length* don't contribute to a polished look. Let's change that by setting the axes labels–called *titles* in Plotly–accordingly.

```{python}
fig.update_layout(
  title_text="Comparison of petals of different Iris species",
  xaxis=dict(title="petal width"),
  yaxis={"title": "petal length"}
)
```

In the code snippet above, both the `xaxis` and the `yaxis` parameter were passed a dictionary. Plotly's documentation uses the notation with `dict(…)` heavily, while I would be more inclined to use the curly braces instead. There is, however, yet another way to define these settings and it is my personal favorite.

```{python}
fig.update_layout(
  title_text="Comparison of petals of different Iris species",
  xaxis_title="petal width",
  yaxis_title="petal length"
)
```

Plotly allows us to flatten the specification of arguments by glueing a settings category (e.g., `xaxis`) with the property we would like to set (e.g., `title`) using an underscore. This speeds up typing a bit.

## Font Size

Next, let's increase the font size used for the title and the axis labels.

```{python}
fig.update_layout(
  title_text="Comparison of petals of different Iris species",
  title_font_size=24,
  xaxis_title="petal width",
  xaxis_title_font_size=16,
  yaxis_title="petal length",
  yaxis_title_font_size=16
)
```

Oops! While Plotly did increase font sizes as instructed, the title no longer fits on the image.

## Margins

Let's fix that by increasing the top margin. And while we're at it, let's also increase the margin to the other sides slightly.

```{python}
fig.update_layout(
  title_text="Comparison of petals of different Iris species",
  title_font_size=24,
  xaxis_title="petal width",
  xaxis_title_font_size=16,
  yaxis_title="petal length",
  yaxis_title_font_size=16,
  margin_t=80,  # top margin
  margin_r=60,  # right margin
  margin_b=60,  # bottom margin
  margin_l=60  # left margin
)
```

This way, when we place the plot on a slide next to other information, it allows the slide to *breathe* a little more. With such short names for the property we aim to adjust (`t`, `r`, `b`, and `l` in the `margin` category), we might as well go for the layout specification using a dictionary. The following code snippet shows how this would look like.

```{python}
fig.update_layout(
  title_text="Comparison of petals of different Iris species",
  title_font_size=24,
  xaxis_title="petal width",
  xaxis_title_font_size=16,
  yaxis_title="petal length",
  yaxis_title_font_size=16,
  margin={"t": 80, "r": 60, "b": 60, "l": 60}
)
```

This concludes our quest to hone our plots 🙂 Note that there are many other properties you can adjust to make your plots truly bespoke. For instance, you can change

- axes (e.g., set the ranges of axes)
- markers (e.g., dots, stars, and triangles depending on the category instead of dots for all categories)
- fonts (font families, sizes and colors)
- the legend (e.g., placing the legend or hiding it alltogether)
- the grid in the background of the chart
- and so on …

If you want to learn more, head over to [Plotly's documentation](https://plotly.com/python/getting-started/).
