import re
import yaml

if __name__ == "__main__":
    # write appendix heading
    sols_chapter = (
        "---\n"
        "format:\n"
        "  html:\n"
        "    respect-user-color-scheme: true\n"
        "    theme:\n"
        '        light: ["style/flatly_customizations.scss", "style/style-light-color-customizations.scss", "style/style-customizations.scss"]\n'
        '        dark: ["style/darkly_customizations.scss", "style/style-dark-color-customizations.scss", "style/style-customizations.scss"]\n'
        "---\n"
    )
    sols_chapter += "\n<!--\n  WARNING: this file is automatically generated by the pre-render script in `scripts/create_solutions_chapter.py`\n-->\n"
    sols_chapter += "# Solutions to Exercises"
    sols_chapter += (
        "\n\n```{python}\n"
        "import pandas as pd\n"
        "```"
    )

    # find list of all chapters from _quarto.yml file
    with open('_quarto.yml') as f:
        quarto_project_dict = yaml.safe_load(f)

    print("🙃"*80, quarto_project_dict["book"]["chapters"])

    parts_list = quarto_project_dict["book"]["chapters"]

    chapters_list = [
        chapter
        for part in parts_list if isinstance(part, dict)
        for chapter in part["chapters"]
    ]

    # for each chapter…
    for chapter in chapters_list:
        # find chapter's title and reference
        with open(chapter, "r") as chapter_file:
            chapter_content = chapter_file.read()
        CHAPTER_HEADING_PATTERN = r"(^|\n)#([\s\S]*?)\{#(sec-[A-Za-z0-9-]+)\}" + "\n"
        if not isinstance(chapter_content, str):
            print("🚨🚨🚨🚨🚨 chapter is not a string")
            raise ValueError(f"chapter {chapter} not found!")
        print("🫣", chapter_content[:20])
        title = re.search(CHAPTER_HEADING_PATTERN, chapter_content).group(2).strip()
        print("    title:", title)
        chapter_ref = re.search(CHAPTER_HEADING_PATTERN, chapter_content).group(3)
        print("    ref:", chapter_ref)

        # add chapter heading to the appendix we try to generate
        sols_chapter += f"\n\n## Solutions for @{chapter_ref}"

        # find all exercises in chapter
        EXERCISE_PATTERN_END = r"[\s\S]*?\n:::(\n|$)"
        EXERCISE_PATTERN = r":::\s*\{#(exr-[A-Za-z0-9-]+)\}" + EXERCISE_PATTERN_END
        exercise_refs = [
            match.group(1)
            for match in re.finditer(EXERCISE_PATTERN, chapter_content, flags=re.DOTALL)
        ]
        # if there are no exercises in the chapter, add this info in the sol chapter
        if not exercise_refs:
            sols_chapter += "\n\nThere are no exercises in this chapter."
            continue
        # for each exercise:
        for exercise_ref in exercise_refs:
            # find corresponding solution in solutions .md file
            solution_ref = exercise_ref.replace("exr", "sol")
            print(f"... tryping to find solution {solution_ref}")
            SOLUTION_WHOLE_PATTERN = r":::\s*\{#" + solution_ref + r"\}" + EXERCISE_PATTERN_END
            with open("appendix-solutions-raw.md", "r") as sols_raw_file:
                sols_raw_content = sols_raw_file.read()
                solution_match_whole = re.search(SOLUTION_WHOLE_PATTERN, sols_raw_content)
                # add solution to sol chapter
                if solution_match_whole is None:
                    print(f"🚨 Solution {solution_ref} not found!")
                else:
                    solution_text_whole = solution_match_whole.group()
                    sols_chapter += "\n\n" + solution_text_whole
                    print(f"✅ Solution {solution_ref} found.")
    
    with open("appendix-solutions.qmd", "w") as sols_chapter_file:
        sols_chapter_file.write(sols_chapter)
